services:
  postgres:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_DB=warehouse_orders
      - POSTGRES_USER=warehouse_admin
      - POSTGRES_PASSWORD=secure_password
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_warehouse.sql
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - warehouse_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warehouse_admin -d warehouse_orders"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: .
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=warehouse_orders
      - DB_LOGIN=warehouse_admin
      - DB_PASSWORD=secure_password
    ports:
      - "5000:5000"
    networks:
      - warehouse_net
    depends_on:
      postgres:
        condition: service_healthy

networks:
  warehouse_net:
